// Regenerates README.md from data/profile.json. Each card's <img title> carries the details its
// hover interaction reveals, because GitHub renders README SVGs as static images.
// Usage: node scripts/readme.mjs
import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const profile = JSON.parse(await readFile(new URL("data/profile.json", root), "utf8"));
const RAW = "https://raw.githubusercontent.com/ABDULMUNAFZ/ABDULMUNAFZ/output";

const attr = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function card({ name, alt, tooltip, caption }) {
  // A blank line would end the Markdown HTML block mid-attribute, so tooltip lines are never empty.
  const title = attr([...tooltip.filter(Boolean), "↗ Click to open the interactive version."].join("\n"));
  return `<a href="${RAW}/${name}-full.svg">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${RAW}/${name}-dark.svg" />
  <source media="(prefers-color-scheme: light)" srcset="${RAW}/${name}-light.svg" />
  <img width="100%" alt="${attr(alt)}" title="${title}" src="${RAW}/${name}-dark.svg" />
</picture>
</a>${caption ? `\n<p align="center"><sub>${caption}</sub></p>` : ""}

<br/>
`;
}

const { about, hackathons, projects, stack, certifications } = profile;
const linked = projects.filter((p) => p.url);

const cards = [
  card({
    name: "calendar-3d",
    alt: "3D contribution calendar for the last 12 months",
    tooltip: ["CONTRIBUTIONS · LAST 12 MONTHS", "Taller, brighter blocks = busier days."],
    caption: "Hover any card for its details · click to open it full-screen and explore.",
  }),
  card({
    name: "about",
    alt: `About: ${about.whoami}`,
    tooltip: ["ABOUT", about.whoami, ...about.rows.map((r) => `${r.key}: ${r.value} (${r.note})`)],
  }),
  card({
    name: "hackathons",
    alt: `Hackathons: ${hackathons.map((h) => `${h.result} ${h.short} (${h.year})`).join(", ")}`,
    tooltip: ["HACKATHONS", ...hackathons.map((h) => `${h.result} · ${h.event} — ${h.venue}, ${h.year}`)],
  }),
  card({
    name: "work",
    alt: `Selected work: ${projects.map((p) => p.title).join(", ")}`,
    tooltip: ["SELECTED WORK", ...projects.flatMap((p, k) => [`${String(k + 1).padStart(2, "0")} ${p.title} — ${p.description}`, `    ${p.stack.join(" · ")}`])],
    caption: linked.map((p) => `<a href="${p.url}">${p.title}</a>`).join(" · "),
  }),
  card({
    name: "stack",
    alt: `Tech stack: ${stack.map((g) => g.items.join(", ")).join(", ")}`,
    tooltip: ["STACK", ...stack.map((g) => `${g.name}: ${g.items.join(", ")}`)],
  }),
  card({
    name: "certifications",
    alt: `Certifications: ${certifications.map((c) => c.issuer).join(", ")}`,
    tooltip: ["CERTIFICATIONS", ...certifications.map((c) => `${c.issuer} — ${c.area}`)],
  }),
  card({
    name: "languages",
    alt: "Languages by code share, plus public repos, stars, followers and pull requests",
    tooltip: ["LANGUAGES & NUMBERS", "Code share across public repos, refreshed every 12 hours."],
  }),
];

const readme = `<a href="https://www.abdulmunaf.in/">
  <img src="./assets/hero.svg" width="100%" alt="Abdul Munaf Z — front-end engineer building interfaces that see, think and speak" />
</a>

<p align="center">
  <a href="https://www.abdulmunaf.in/"><img src="https://img.shields.io/badge/Portfolio-abdulmunaf.in-1A1D23?style=flat-square&labelColor=FF7A3D" alt="Portfolio" /></a>
  <a href="https://linkedin.com/in/abdul-munaf-z-6380a8251"><img src="https://img.shields.io/badge/LinkedIn-Abdul_Munaf_Z-1A1D23?style=flat-square&labelColor=2B2F36" alt="LinkedIn" /></a>
  <a href="mailto:z.abdulmunaf@gmail.com"><img src="https://img.shields.io/badge/Email-z.abdulmunaf@gmail.com-1A1D23?style=flat-square&logo=gmail&logoColor=FF7A3D&labelColor=2B2F36" alt="Email" /></a>
  <img src="https://komarev.com/ghpvc/?username=ABDULMUNAFZ&label=views&color=1A1D23&style=flat-square" alt="Profile views" />
  <img src="https://img.shields.io/github/followers/ABDULMUNAFZ?label=followers&style=flat-square&color=1A1D23&labelColor=2B2F36" alt="Followers" />
</p>

<br/>

${cards.join("\n")}
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${RAW}/snake-dark.svg" />
  <source media="(prefers-color-scheme: light)" srcset="${RAW}/snake.svg" />
  <img width="100%" alt="Contribution snake" src="${RAW}/snake.svg" />
</picture>

<p align="center"><sub>Every graphic here is generated by <a href="./scripts"><code>scripts/</code></a> from <a href="./data/profile.json"><code>data/profile.json</code></a> and live GitHub data, refreshed every 12 hours.</sub></p>
`;

await writeFile(new URL("README.md", root), readme);
console.log("wrote README.md");
